### PR TITLE
Support yearmon YYYYxMM dates

### PR DESCRIPTION
**Pull request by gvfarns**
We may also think about adding yearqtr support at some point "1980 Q1"

### CODE REVIEW

**Comment by jalvesaq** [comment]
Is `yearmon` from `zoo` package? We cannot support every R package because colorout would become too complex, difficult to maintain and, perhaps, slow.
I will try to think in a way of letting users dynamically setting their own patterns to be colorized.

**Comment by gvfarns** [comment]
The zoo package is not the relevant thing here. There are only a handful of ways dates are represented and they are not all of equal importance in R. R addresses date formatting by adhering to the ISO 8601 standard, which specifies YYYY-MM-DD and YYYY-MM as well as the time formats used in R.  There are many formats that are currently supported by colorout that are not supported by R or ISO 8601, like DD/MM/YYYY.

I'm sympathetic to the desire to keep colorout simple, but date formats that are used should be those supported by the R standard.  Something printed as DD/MM/YYYY would be a character string and should be formatted as such, as opposed to an R date (whether day, month, or date/time).

Dynamically setting patterns sounds cool, if you can do it without slowing colorout down. In the mean time I believe the official R standards should be prioritized.

**Comment by jalvesaq** [comment]
I agree that colorout should support only the date format output by vanilla R. I will try to add support for dynamically defining patterns to be colorized and then remove the support for what is not standard.

**Comment by jalvesaq** [comment]
@gvfarns, please, try the branch https://github.com/jalvesaq/colorout/tree/add_pattern

**Comment by gvfarns** [comment]
Doesn't work for me at the present moment.

Screenshot from 2019-07-08 10-22-28

**Comment by jalvesaq** [comment]
It should be fixed now.

**Comment by gvfarns** [comment]
Thanks. Added patterns now work but if one is matched, it breaks other patterns.

Screenshot from 2019-07-08 13-28-51

Probably one needs the ability to order these patterns, so that strings that match more than one pattern will be colored by the first in the list.

Have you looked at the performance hit from this approach? If it is small, perhaps it would be feasible to get rid of all hard-coded patterns and instead have a default set of patterns loaded, which the user can change that they will.  That would be the most general solution, similar to what an editor would do (for example, vim syntax highlighting).

Alternatively, patterns could include an end-of-word marker of some kind so that "2019-01-02" would not match a pattern intended to get "2019-01" because it knows the end of word has not arrived.

**Comment by jalvesaq** [comment]
Custom patterns have priority over default patterns and the last pattern added is the first to be highlighted:

```
cat("Does the colorizing of both 2019-07 and 2019-07-01 work?\n")
addPattern("[1-2][0-9][0-9][0-9]-[0-1][0-9]", 39)
cat("Does the colorizing of both 2019-07 and 2019-07-01 work?\n")
addPattern("[1-2][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]", 37)
cat("Does the colorizing of both 2019-07 and 2019-07-01 work?\n")
```

**Comment by jalvesaq** [comment]
> Have you looked at the performance hit from this approach? If it is small, perhaps it would be feasible to get rid of all hard-coded patterns [...]

I didn't look at the performance yet, but even it is only a bit slower, the hard-coded patterns should be kept because speed is the absolute priority.

**Comment by gvfarns** [comment]
If the hard-coded patterns are evaluated only after the custom patterns, then isn't the performance hit maximized? If text matches a hard-coded pattern, it must go through evaluation of all of the custom patterns before hitting the hard-coded ones. Right?

**Comment by jalvesaq** [comment]
>If the hard-coded patterns are evaluated only after the custom patterns, then isn't the performance hit maximized?

The hard-coded patterns are evaluated only if there is no match with custom patterns. Note the `if(haspttrn) continue` statement.

> If text matches a hard-coded pattern, it must go through evaluation of all of the custom patterns before hitting the hard-coded ones. Right?

Yes. And the same is true for the hard-coded patterns that are the last ones in the code. The last pattern, that of negative numbers, is tested only after all other tests have had negative results.

**Comment by jalvesaq** [comment]
I added the recognition of `*` as a special character in the pattern: https://github.com/jalvesaq/colorout/commit/6fd64b1c9faf240024f687bec28f333e1a0bd131
Still, it's not possible to replace the hard-coded patterns because two of them use the `!=` operator in their conditions.

**Comment by jalvesaq** [comment]
Revisiting this issue, I noted that my comment above (https://github.com/jalvesaq/colorout/pull/25#issuecomment-509363691) solves the problem described in the title of the issue...

**Pull request closed without merging**
